### PR TITLE
Add support for asymmetric authentication

### PR DESCRIPTION
**Pull request by LDVG**
This is a rebase of #12 on top of master, applying the unresolved review comments in the process.

Note that this contains breaking changes to the `AuthSession` class, see commit messages for details.

Closes #12.

### CODE REVIEW

**Review by elibon99 — APPROVED** [review]

**Comment by dainnilsson** [comment]
I think this looks very good. I think there is some code in `create_session_asymmetric` that we can (later) break out and re-use to support creating a session using a YubiKey with HSMAuth. That should probably be a separate `create_session_xxx` method.

I wonder if the device public key should be passed in to the method rather than reading it from the HSM to allow for caching (and noticing changes to) the public key. Any thoughts on that?

**Comment by LDVG** [comment]
> I wonder if the device public key should be passed in to the method rather than reading it from the HSM to allow for caching (and noticing changes to) the public key. Any thoughts on that?

Makes sense to me.

> EDIT: I think having the public key as an optional keyword argument probably makes sense, and when omitted it uses the current behavior.

Agreed. I pushed a new commit that implements something along these lines and a complimentary test case.

**Review by dainnilsson — APPROVED** [review]

**Comment by elibon99** [comment]
Just a minor detail - in the docstring of the AuthSession class ([here](https://github.com/Yubico/python-yubihsm/blob/46ff4f43bfff3c3cf50ff3c2a43627baf6e67ca0/yubihsm/core.py#L375-L376)), it would be nice to mention `create_session_asymmetric` as a method for instantiating the AuthSession class.

**Comment by LDVG** [comment]
> Just a minor detail - in the docstring of the AuthSession class ([here](https://github.com/Yubico/python-yubihsm/blob/46ff4f43bfff3c3cf50ff3c2a43627baf6e67ca0/yubihsm/core.py#L375-L376)), it would be nice to mention `create_session_asymmetric` as a method for instantiating the AuthSession class.

Fixed.

**Pull request merged**
